model:
  root_dir: "artifacts\\data_transformation"
  data_path: "artifacts\\data_transformation\\sampled_dataset"
  checkpoint: "google-t5/t5-small"
  max_length: 1024
  min_length: 40
  output_dir: "artifacts\\models"
  learning_rate: 2e-5
  train_batch_size: 16
  eval_batch_size: 16
  weight_decay: 0.01
  save_total_limit: 3
  num_train_epochs: 4
  prefix: "summarize: "
  push_to_hub: false
  device: 