artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://www.kaggle.com/api/v1/datasets/download/rounakbanik/ted-talks?dataset_version_number=3
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_dir: artifacts/data_ingestion
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["ted_main.csv", "transcripts.csv"]
  required_columns: ["title", "transcript"]
