artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://www.kaggle.com/api/v1/datasets/download/rounakbanik/ted-talks?dataset_version_number=3
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_dir: artifacts/data_ingestion
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["ted_main.csv", "transcripts.csv"]
  required_columns: ["title", "transcript"]


data_standardization:
  input_file_directory: "artifacts/data_ingestion"
  output_dir: "artifacts/data_standardization"
  nltk_dir: "artifacts/models"
  output_file: "standardized_data.csv"
  ALL_REQUIRED_FILES: ["ted_main.csv", "transcripts.csv"]
  text_columns: ['description', 'title', 'transcript']
  relevant_fields: ['description', 'tags', 'title', 'ratings', 'url']
  merging_key: 'url'
  

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: "artifacts/data_standardization/standardized_data.csv"
  checkpoint: "google-t5/t5-small"
  max_length: 1024
  min_length: 40
  output_dir: artifacts/data_transformation
  prefix: "summarize: "
  sample_size: 20

